# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"
# require OpenZepplin Contracts